services:

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "10004:10004"
    depends_on:
      - syncslot_db
      - syncslot_db_test
      - cache
    volumes:
      - ./storage:/syncslot/backend/storage
    environment:
      REDIS_HOST: cache
      REDIS_PORT: 6379
    networks:
      - syncslot_network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - syncslot_network
    environment:
      VITE_API_URL: "http://backend:10004"

  syncslot_db:
    image: postgres:17.1
    container_name: "syncslot_db"
    hostname: "syncslot_db"
    volumes:
      - syncslot_data:/var/lib/postgresql/data/
    restart: always
    environment:
      POSTGRES_DB: syncslot_db
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
    ports:
      - "5432:5432"
    networks:
      - syncslot_network

  syncslot_db_test:
    image: postgres:17.1
    container_name: "syncslot_db_test"
    hostname: "db_test"
    restart: always
    environment:
      POSTGRES_DB: syncslot_db_test
      POSTGRES_USER: pguser_test
      POSTGRES_PASSWORD: pgpassword_test
    ports:
      - "54349:5432"
    networks:
      - syncslot_network

  cache:
    image: redis:7-alpine
    container_name: syncslot_cache
    hostname: cache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - syncslot_network

volumes:
  syncslot_data:

networks:
  syncslot_network:
    driver: bridge